namespace SistemaAlquilerVehiculos.Formularios
{
    partial class FrmVehiculos
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblId;
        private System.Windows.Forms.Label lblPlaca;
        private System.Windows.Forms.Label lblMarca;
        private System.Windows.Forms.Label lblModelo;
        private System.Windows.Forms.Label lblAnio;
        private System.Windows.Forms.Label lblTipo;
        private System.Windows.Forms.Label lblTarifa;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.TextBox txtId;
        private System.Windows.Forms.TextBox txtPlaca;
        private System.Windows.Forms.TextBox txtMarca;
        private System.Windows.Forms.TextBox txtModelo;
        private System.Windows.Forms.TextBox txtAnio;
        private System.Windows.Forms.TextBox txtTarifaDiaria;
        private System.Windows.Forms.ComboBox cboTipoVehiculo;
        private System.Windows.Forms.ComboBox cboEstadoVehiculo;
        private System.Windows.Forms.Button btnNuevo;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Button btnCambiarEstadoActivo;
        private System.Windows.Forms.CheckBox chkMostrarInactivos;
        private System.Windows.Forms.DataGridView dgvVehiculos;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblId = new System.Windows.Forms.Label();
            this.lblPlaca = new System.Windows.Forms.Label();
            this.lblMarca = new System.Windows.Forms.Label();
            this.lblModelo = new System.Windows.Forms.Label();
            this.lblAnio = new System.Windows.Forms.Label();
            this.lblTipo = new System.Windows.Forms.Label();
            this.lblTarifa = new System.Windows.Forms.Label();
            this.lblEstado = new System.Windows.Forms.Label();
            this.txtId = new System.Windows.Forms.TextBox();
            this.txtPlaca = new System.Windows.Forms.TextBox();
            this.txtMarca = new System.Windows.Forms.TextBox();
            this.txtModelo = new System.Windows.Forms.TextBox();
            this.txtAnio = new System.Windows.Forms.TextBox();
            this.txtTarifaDiaria = new System.Windows.Forms.TextBox();
            this.cboTipoVehiculo = new System.Windows.Forms.ComboBox();
            this.cboEstadoVehiculo = new System.Windows.Forms.ComboBox();
            this.btnNuevo = new System.Windows.Forms.Button();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.btnCambiarEstadoActivo = new System.Windows.Forms.Button();
            this.chkMostrarInactivos = new System.Windows.Forms.CheckBox();
            this.dgvVehiculos = new System.Windows.Forms.DataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgvVehiculos)).BeginInit();
            this.SuspendLayout();
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.Location = new System.Drawing.Point(22, 19);
            this.lblTitulo.Text = "Administración de vehículos";
            this.lblId.AutoSize = true;
            this.lblId.Location = new System.Drawing.Point(24, 69);
            this.lblId.Text = "ID:";
            this.lblPlaca.AutoSize = true;
            this.lblPlaca.Location = new System.Drawing.Point(113, 69);
            this.lblPlaca.Text = "Placa:";
            this.lblMarca.AutoSize = true;
            this.lblMarca.Location = new System.Drawing.Point(284, 69);
            this.lblMarca.Text = "Marca:";
            this.lblModelo.AutoSize = true;
            this.lblModelo.Location = new System.Drawing.Point(453, 69);
            this.lblModelo.Text = "Modelo:";
            this.lblAnio.AutoSize = true;
            this.lblAnio.Location = new System.Drawing.Point(24, 123);
            this.lblAnio.Text = "Año:";
            this.lblTipo.AutoSize = true;
            this.lblTipo.Location = new System.Drawing.Point(164, 123);
            this.lblTipo.Text = "Tipo:";
            this.lblTarifa.AutoSize = true;
            this.lblTarifa.Location = new System.Drawing.Point(336, 123);
            this.lblTarifa.Text = "Tarifa diaria:";
            this.lblEstado.AutoSize = true;
            this.lblEstado.Location = new System.Drawing.Point(508, 123);
            this.lblEstado.Text = "Estado:";
            this.txtId.Location = new System.Drawing.Point(27, 87);
            this.txtId.ReadOnly = true;
            this.txtId.Size = new System.Drawing.Size(60, 23);
            this.txtPlaca.Location = new System.Drawing.Point(116, 87);
            this.txtPlaca.MaxLength = 20;
            this.txtPlaca.Size = new System.Drawing.Size(145, 23);
            this.txtMarca.Location = new System.Drawing.Point(287, 87);
            this.txtMarca.MaxLength = 50;
            this.txtMarca.Size = new System.Drawing.Size(145, 23);
            this.txtModelo.Location = new System.Drawing.Point(456, 87);
            this.txtModelo.MaxLength = 50;
            this.txtModelo.Size = new System.Drawing.Size(145, 23);
            this.txtAnio.Location = new System.Drawing.Point(27, 141);
            this.txtAnio.Size = new System.Drawing.Size(112, 23);
            this.cboTipoVehiculo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTipoVehiculo.Location = new System.Drawing.Point(167, 141);
            this.cboTipoVehiculo.Size = new System.Drawing.Size(145, 23);
            this.txtTarifaDiaria.Location = new System.Drawing.Point(339, 141);
            this.txtTarifaDiaria.Size = new System.Drawing.Size(145, 23);
            this.cboEstadoVehiculo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboEstadoVehiculo.Location = new System.Drawing.Point(511, 141);
            this.cboEstadoVehiculo.Size = new System.Drawing.Size(145, 23);
            this.btnNuevo.Location = new System.Drawing.Point(27, 198);
            this.btnNuevo.Size = new System.Drawing.Size(110, 35);
            this.btnNuevo.Text = "Nuevo";
            this.btnNuevo.UseVisualStyleBackColor = true;
            this.btnNuevo.Click += new System.EventHandler(this.btnNuevo_Click);
            this.btnGuardar.Location = new System.Drawing.Point(145, 198);
            this.btnGuardar.Size = new System.Drawing.Size(175, 35);
            this.btnGuardar.Text = "Guardar vehículo";
            this.btnGuardar.UseVisualStyleBackColor = true;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            this.btnCambiarEstadoActivo.Location = new System.Drawing.Point(328, 198);
            this.btnCambiarEstadoActivo.Size = new System.Drawing.Size(230, 35);
            this.btnCambiarEstadoActivo.Text = "Activar / desactivar seleccionado";
            this.btnCambiarEstadoActivo.UseVisualStyleBackColor = true;
            this.btnCambiarEstadoActivo.Click += new System.EventHandler(this.btnCambiarEstadoActivo_Click);
            this.chkMostrarInactivos.AutoSize = true;
            this.chkMostrarInactivos.Location = new System.Drawing.Point(27, 257);
            this.chkMostrarInactivos.Text = "Mostrar vehículos inactivos";
            this.chkMostrarInactivos.UseVisualStyleBackColor = true;
            this.chkMostrarInactivos.CheckedChanged += new System.EventHandler(this.chkMostrarInactivos_CheckedChanged);
            this.dgvVehiculos.AllowUserToAddRows = false;
            this.dgvVehiculos.AllowUserToDeleteRows = false;
            this.dgvVehiculos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvVehiculos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvVehiculos.Location = new System.Drawing.Point(27, 288);
            this.dgvVehiculos.MultiSelect = false;
            this.dgvVehiculos.ReadOnly = true;
            this.dgvVehiculos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvVehiculos.Size = new System.Drawing.Size(629, 270);
            this.dgvVehiculos.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvVehiculos_CellClick);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(688, 589);
            this.Controls.Add(this.dgvVehiculos);
            this.Controls.Add(this.chkMostrarInactivos);
            this.Controls.Add(this.btnCambiarEstadoActivo);
            this.Controls.Add(this.btnGuardar);
            this.Controls.Add(this.btnNuevo);
            this.Controls.Add(this.cboEstadoVehiculo);
            this.Controls.Add(this.txtTarifaDiaria);
            this.Controls.Add(this.cboTipoVehiculo);
            this.Controls.Add(this.txtAnio);
            this.Controls.Add(this.txtModelo);
            this.Controls.Add(this.txtMarca);
            this.Controls.Add(this.txtPlaca);
            this.Controls.Add(this.txtId);
            this.Controls.Add(this.lblEstado);
            this.Controls.Add(this.lblTarifa);
            this.Controls.Add(this.lblTipo);
            this.Controls.Add(this.lblAnio);
            this.Controls.Add(this.lblModelo);
            this.Controls.Add(this.lblMarca);
            this.Controls.Add(this.lblPlaca);
            this.Controls.Add(this.lblId);
            this.Controls.Add(this.lblTitulo);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Name = "FrmVehiculos";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Administración de vehículos";
            this.Load += new System.EventHandler(this.FrmVehiculos_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvVehiculos)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
