// <auto-generated />
namespace SistemaAlquilerVehiculos.Properties
{
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new global::System.Resources.ResourceManager("SistemaAlquilerVehiculos.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }
    }
}
